task_type: multiclass
normalize: true
use_pca: false
pca_variance: 0.95
train_data_path: Benchmark_data\dataset3\multiclass\80\train.csv
val_data_path: Benchmark_data\dataset3\multiclass\80\val.csv
test_data_path: Benchmark_data\dataset3\multiclass\80\test.csv
batch_size: 8192
