benchmark:

  datasets:

    - name: dataset1_binary_50
      train: Benchmark_data/dataset1/binary/50/train.csv
      val: Benchmark_data/dataset1/binary/50/val.csv
      test: Benchmark_data/dataset1/binary/50/test.csv
      num_class: 2
      class_names: [Normal, Attack]

    - name: dataset1_binary_60
      train: Benchmark_data/dataset1/binary/60/train.csv
      val: Benchmark_data/dataset1/binary/60/val.csv
      test: Benchmark_data/dataset1/binary/60/test.csv
      num_class: 2
      class_names: [Normal, Attack]

  models:
    - dnn
    - cnn
    - mlp
    - rad_ffnn
    - tcn_transformer
